// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThoughtFocus.Common.WorkFlowDataAccess;

namespace ThoughtFocus.Common.WorkFlowDataAccess.Migrations
{
    [DbContext(typeof(WorkFlowContext))]
    [Migration("20210503032507_DMLFundUtilizationSeedingForWF")]
    partial class DMLFundUtilizationSeedingForWF
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.ConditionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ConditionType", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.LocalizeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LocalizeType", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.ParameterPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ParameterPurpose", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.RestrictionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RestrictionType", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.TransitionClassifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TransitionClassifier", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.TriggerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TriggerType", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("ActionDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinitionForActivity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ActionDefinitionID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActivityDefinitionID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPostExecution")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ActionDefinitionID");

                    b.HasIndex("ActivityDefinitionID");

                    b.ToTable("ActionDefinitionForActivity", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActivityDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAutoSchemeUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForSetState")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("ActivityDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionExecuteRule", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("ActorDefinitionExecuteRule", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionIsIdentity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("ActorDefinitionIsIdentity", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionIsInRole", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("ActorDefinitionIsInRole", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.CommandDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommandIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("CommandDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ConditionDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Action_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("ConditionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ResultOnPreExecution")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("Action_ID");

                    b.HasIndex("ConditionTypeID");

                    b.ToTable("ConditionDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.LocalizeDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("LocalizeTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("LocalizeTypeID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("LocalizeDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ParameterDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurposeID")
                        .HasColumnType("int");

                    b.Property<string>("SerializedDefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PurposeID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("ParameterDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ParameterDefinitionForAction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ActionDefinitionID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInputParameter")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("ParameterDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ActionDefinitionID");

                    b.HasIndex("ParameterDefinitionID");

                    b.ToTable("ParameterDefinitionForAction", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.RestrictionDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ActorDefinitionExecuteRule_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActorDefinitionIsIdentity_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActorDefinitionIsInRole_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("RestrictionType_Id")
                        .HasColumnType("int");

                    b.Property<long?>("Transition_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ActorDefinitionExecuteRule_ID");

                    b.HasIndex("ActorDefinitionIsIdentity_ID");

                    b.HasIndex("ActorDefinitionIsInRole_ID");

                    b.HasIndex("RestrictionType_Id");

                    b.HasIndex("Transition_ID");

                    b.ToTable("RestrictionDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TransitionDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConditionID")
                        .HasColumnType("bigint");

                    b.Property<long?>("FromID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ToID")
                        .HasColumnType("bigint");

                    b.Property<int>("TransitionClassifierID")
                        .HasColumnType("int");

                    b.Property<long>("TriggerID")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ConditionID");

                    b.HasIndex("FromID");

                    b.HasIndex("ToID");

                    b.HasIndex("TransitionClassifierID");

                    b.HasIndex("TriggerID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("TransitionDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TransitionValidationDefination", b =>
                {
                    b.Property<long>("TransitionValidationDefinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<long>("TransitionDefinitionID")
                        .HasColumnType("bigint");

                    b.Property<string>("TransitionValidationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ValidationDefinationID")
                        .HasColumnType("bigint");

                    b.HasKey("TransitionValidationDefinationID");

                    b.HasIndex("TransitionDefinitionID");

                    b.HasIndex("ValidationDefinationID");

                    b.ToTable("TransitionValidationDefination", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TriggerDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommandID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CommandID");

                    b.HasIndex("TypeId");

                    b.ToTable("TriggerDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ValidationDefination", b =>
                {
                    b.Property<long>("ValidationDefinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ValidationDefinationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationDefinationErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationDefinationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ValidationTypeID")
                        .HasColumnType("bigint");

                    b.HasKey("ValidationDefinationID");

                    b.HasIndex("ValidationTypeID");

                    b.ToTable("ValidationDefination", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ValidationFieldDefination", b =>
                {
                    b.Property<long>("ValidationFieldDefinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ValidationDefinationID")
                        .HasColumnType("bigint");

                    b.Property<string>("ValidationFieldDefinationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationFieldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValidationFieldDefinationID");

                    b.HasIndex("ValidationDefinationID");

                    b.ToTable("ValidationFieldDefination", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ValidationType", b =>
                {
                    b.Property<long>("ValidationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ValidationTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValidationTypeID");

                    b.ToTable("ValidationType", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DesignerModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("WorkflowDefinition", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.PersistanceModel.WorkflowProcessInstance", b =>
                {
                    b.Property<long>("WorkflowProcessInstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeterminingParametersChanged")
                        .HasColumnType("bit");

                    b.Property<string>("PreviousActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousActivityForDirect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousActivityForReverse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousStateForDirect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousStateForReverse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProcessInstanceID")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkflowDefinitionID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowProcessInstanceID");

                    b.HasIndex("WorkflowDefinitionID");

                    b.ToTable("WorkflowProcessInstance", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.PersistanceModel.WorkflowProcessInstancePersistence", b =>
                {
                    b.Property<Guid>("WorkflowProcessInstancePersistenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProcessInstanceID")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkFlowDefinationID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowProcessInstancePersistenceID");

                    b.ToTable("WorkflowProcessInstancePersistence", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.PersistanceModel.WorkflowProcessInstanceStatus", b =>
                {
                    b.Property<long>("WorkflowProcessInstanceStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Lock")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProcessInstanceID")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("WorkFlowDefinationID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowProcessInstanceStatusID");

                    b.ToTable("WorkflowProcessInstanceStatus", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.PersistanceModel.WorkflowProcessTimer", b =>
                {
                    b.Property<Guid>("WorkflowProcessTimerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ignore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextExecutionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProcessInstanceID")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkFlowDefinationID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowProcessTimerID");

                    b.ToTable("WorkflowProcessTimer", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.PersistanceModel.WorkflowProcessTransitionHistory", b =>
                {
                    b.Property<Guid>("WorkflowProcessTransitionHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorIdentityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutorIdentityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromStateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinalised")
                        .HasColumnType("bit");

                    b.Property<long>("ProcessInstanceID")
                        .HasColumnType("bigint");

                    b.Property<string>("ToActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransitionClassifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransitionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TriggerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WorkFlowDefinationID")
                        .HasColumnType("bigint");

                    b.HasKey("WorkflowProcessTransitionHistoryID");

                    b.ToTable("WorkflowProcessTransitionHistory", "WorkFlow");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Actions")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinitionForActivity", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinition", "ActionDefinition")
                        .WithMany()
                        .HasForeignKey("ActionDefinitionID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActivityDefinition", "ActivityDefinition")
                        .WithMany("ActionDefinitionForActivities")
                        .HasForeignKey("ActivityDefinitionID");

                    b.Navigation("ActionDefinition");

                    b.Navigation("ActivityDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActivityDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Activities")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionExecuteRule", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("ActorDefinitionExecuteRules")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionIsIdentity", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("ActorDefinitionIsIdentities")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionIsInRole", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("ActorDefinitionIsInRoles")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.CommandDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Commands")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ConditionDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinition", "Action")
                        .WithMany()
                        .HasForeignKey("Action_ID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.ConditionType", "ConditionType")
                        .WithMany()
                        .HasForeignKey("ConditionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("ConditionType");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.LocalizeDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.LocalizeType", "LocalizeType")
                        .WithMany()
                        .HasForeignKey("LocalizeTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Localization")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalizeType");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ParameterDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.ParameterPurpose", "Purpose")
                        .WithMany()
                        .HasForeignKey("PurposeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Parameters")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purpose");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ParameterDefinitionForAction", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinition", null)
                        .WithMany("ParameterDefinitionForActions")
                        .HasForeignKey("ActionDefinitionID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ParameterDefinition", "ParameterDefinition")
                        .WithMany()
                        .HasForeignKey("ParameterDefinitionID");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.RestrictionDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionExecuteRule", "ActorDefinitionExecuteRule")
                        .WithMany()
                        .HasForeignKey("ActorDefinitionExecuteRule_ID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionIsIdentity", "ActorDefinitionIsIdentity")
                        .WithMany()
                        .HasForeignKey("ActorDefinitionIsIdentity_ID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActorDefinitionIsInRole", "ActorDefinitionIsInRole")
                        .WithMany()
                        .HasForeignKey("ActorDefinitionIsInRole_ID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.RestrictionType", "RestrictionType")
                        .WithMany()
                        .HasForeignKey("RestrictionType_Id");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.TransitionDefinition", "Transition")
                        .WithMany("Restrictions")
                        .HasForeignKey("Transition_ID");

                    b.Navigation("ActorDefinitionExecuteRule");

                    b.Navigation("ActorDefinitionIsIdentity");

                    b.Navigation("ActorDefinitionIsInRole");

                    b.Navigation("RestrictionType");

                    b.Navigation("Transition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TransitionDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ConditionDefinition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActivityDefinition", "From")
                        .WithMany()
                        .HasForeignKey("FromID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ActivityDefinition", "To")
                        .WithMany()
                        .HasForeignKey("ToID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.TransitionClassifier", "TransitionClassifier")
                        .WithMany()
                        .HasForeignKey("TransitionClassifierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.TriggerDefinition", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("From");

                    b.Navigation("To");

                    b.Navigation("TransitionClassifier");

                    b.Navigation("Trigger");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TransitionValidationDefination", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.TransitionDefinition", "TransitionDefinition")
                        .WithMany("TransitionValidationDefinations")
                        .HasForeignKey("TransitionDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ValidationDefination", "ValidationDefination")
                        .WithMany()
                        .HasForeignKey("ValidationDefinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransitionDefinition");

                    b.Navigation("ValidationDefination");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TriggerDefinition", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.CommandDefinition", "Command")
                        .WithMany()
                        .HasForeignKey("CommandID");

                    b.HasOne("ThoughtFocus.Common.Workflow.Core.EnumerationHelpers.TriggerType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Command");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ValidationDefination", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ValidationType", "ValidationType")
                        .WithMany()
                        .HasForeignKey("ValidationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidationType");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ValidationFieldDefination", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.ValidationDefination", "ValidationDefination")
                        .WithMany("ValidationFieldDefinations")
                        .HasForeignKey("ValidationDefinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidationDefination");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.PersistanceModel.WorkflowProcessInstance", b =>
                {
                    b.HasOne("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActionDefinition", b =>
                {
                    b.Navigation("ParameterDefinitionForActions");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ActivityDefinition", b =>
                {
                    b.Navigation("ActionDefinitionForActivities");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.TransitionDefinition", b =>
                {
                    b.Navigation("Restrictions");

                    b.Navigation("TransitionValidationDefinations");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.ValidationDefination", b =>
                {
                    b.Navigation("ValidationFieldDefinations");
                });

            modelBuilder.Entity("ThoughtFocus.Common.Workflow.Core.Model.WorkflowDefinition", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Activities");

                    b.Navigation("ActorDefinitionExecuteRules");

                    b.Navigation("ActorDefinitionIsIdentities");

                    b.Navigation("ActorDefinitionIsInRoles");

                    b.Navigation("Commands");

                    b.Navigation("Localization");

                    b.Navigation("Parameters");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
