using Microsoft.EntityFrameworkCore.Migrations;

namespace ThoughtFocus.DataAccess.Migrations
{
    public partial class seeding_HelpfulGuideTemplate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {  
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[TemplateTypes] ON ");
            migrationBuilder.Sql("INSERT [Master].[TemplateTypes] ([ID], [Name], [IsActive], [DisplayOrder]) VALUES (1, 'Business Profile',1,1)");
            migrationBuilder.Sql("INSERT [Master].[TemplateTypes] ([ID], [Name],  [IsActive], [DisplayOrder]) VALUES (2, 'Funding Application',1,2)");
            migrationBuilder.Sql("INSERT [Master].[TemplateTypes] ([ID], [Name], [IsActive], [DisplayOrder]) VALUES (3, 'Documents',1,3)");
            migrationBuilder.Sql("INSERT [Master].[TemplateTypes] ([ID],[Name],  [IsActive], [DisplayOrder]) VALUES (4, 'Review',1,4)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[TemplateTypes] OFF ");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[HelpfulGuideTemplates] ON ");
            migrationBuilder.Sql("INSERT [Master].[HelpfulGuideTemplates] ([ID],[Body],[IsActive],[TypeID]) VALUES (1, '<div>Helpful Guide and FAQs </div><div style=''box-sizing: border-box; margin: 0rem; padding: 0rem; color: rgb(50, 43, 43); font-family: Motiva-Sans, sans-serif; font-size: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 1px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;''><h6 data-v-73f054b7='' style=''box-sizing: border-box; margin: 2rem 0px; padding: 0rem; font-weight: bold; line-height: 1.2; font-size: 1.6rem; text-transform: capitalize;''>Fill Requirements</h6> <p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>The information provided should be for the business not the business owner.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>Please complete your business profile to start your application and register your business into our system.</p> </div> <p><br></p>',1,1)");
            migrationBuilder.Sql("INSERT [Master].[HelpfulGuideTemplates] ([ID],[Body],[IsActive],[TypeID]) VALUES (2, '<h4 data-v-6d9f7706='' style=''box-sizing: border-box; margin: 0px 0px 1.5rem; padding: 0px; font-weight: 400; line-height: 1.2; font-size: 2.4rem; color: rgb(50, 43, 43); font-family: Motiva-Sans, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 1px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;''>Helpful Guide and FAQs</h4> <div class=''description'' data-v-6d9f7706='' style=''box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(50, 43, 43); font-family: Motiva-Sans, sans-serif; font-size: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 1px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;''> <h6 data-v-6d9f7706='' style=''box-sizing: border-box; margin: 2rem 0px; padding: 0px; font-weight: 700; line-height: 1.2; font-size: 1.6rem; text-transform: capitalize;''>Fill Requirements</h6> <p data-v-6d9f7706='' style=''box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; font-size: 1.4rem;''>Funding amount must be $10,000.</p> <p data-v-6d9f7706='' style=''box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; font-size: 1.4rem;''><b data-v-6d9f7706='' style=''box-sizing: border-box; margin: 0px; padding: 0px; font-weight: bolder;''>Purpose of Funds: </b>Provide brief description of need such as online ordering system, food delivery software, replacement oven, hire web designer.</p> </div> <p><br></p>',1,2)");
            migrationBuilder.Sql("INSERT [Master].[HelpfulGuideTemplates] ([ID],[Body],[IsActive],[TypeID]) VALUES (3, '<h4 data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1.5rem; padding: 0rem; font-weight: normal; line-height: 1.2; font-size: 2.4rem; color: rgb(50, 43, 43); font-family: Motiva-Sans, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 1px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;''>Helpful Guide and FAQs</h4> <div style=''box-sizing: border-box; margin: 0rem; padding: 0rem; color: rgb(50, 43, 43); font-family: Motiva-Sans, sans-serif; font-size: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 1px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;''> <p data-v-73f054b7=''style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>Proof of Ownership can include tax return with IRS Schedule C; copy of DBA Certificate; articles of incorporation; or articles of organization.</p></div>' ,1,3)");
            migrationBuilder.Sql("INSERT [Master].[HelpfulGuideTemplates] ([ID],[Body],[IsActive],[TypeID]) VALUES (4, '<h4>Helpful Guide and FAQs</h4><div style=''> <p ><b ><u >Next Steps:</u></b></p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>1. Review your application for completeness.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>2. Submit application to initiate the review process.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>3. Your application will be reviewed to ensure all required information is provided. It will either be accepted as complete or additional information will be requested.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>4. Once your application is accepted as complete, then it will be reviewed for approval.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>5. You will be informed if application has been approved or rejected.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>6. If your application is approved, you will get an email with a link to this review page to accepted our agreement terms.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>7. Once you have accepted the terms of the agreement, the funding process will begin.</p><p data-v-73f054b7='' style=''box-sizing: border-box; margin: 0px 0rem 1rem; padding: 0rem; font-size: 1.4rem;''>8. You will be notified by email that funds have been distributed to your account on the ACH form.</p> </div>',1,4)");
            migrationBuilder.Sql("INSERT [Master].[HelpfulGuideTemplates] ([ID],[Body],[IsActive],[TypeID]) VALUES (5,  '<h4 >Helpful Guide and FAQs</h4> <div> <h6>Funding amount must be $10,000.</p><p ><b>Purpose of Funds: </b>Provide brief description of need such as equipment, hire web designer, purchase supplies.</p> </div>',1,2)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[HelpfulGuideTemplates] OFF ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("delete from [Master].[TemplateTypes]  where ID between 1 and 4");
            migrationBuilder.Sql("delete from [Master].[HelpfulGuideTemplates]  where ID between 1 and 5");
        }
    }
}
