using Microsoft.EntityFrameworkCore.Migrations;

namespace ThoughtFocus.DataAccess.Migrations
{
    public partial class InitialdataSeedings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[AccountStatus] ON ");
            migrationBuilder.Sql("INSERT [Master].[AccountStatus] ([AccountStatusID], [AccountStatusName], [Description], IsActive) VALUES (1, N'NotCreated', N'Not Created', 1)");
            migrationBuilder.Sql("INSERT [Master].[AccountStatus] ([AccountStatusID], [AccountStatusName], [Description], IsActive) VALUES (2, N'RequestPending', N'Request Pending', 1)");
            migrationBuilder.Sql("INSERT [Master].[AccountStatus] ([AccountStatusID], [AccountStatusName], [Description], IsActive) VALUES (3, N'RequestRejected', N'Request Rejected', 1)");
            migrationBuilder.Sql("INSERT [Master].[AccountStatus] ([AccountStatusID], [AccountStatusName], [Description], IsActive) VALUES (4, N'RequestAccepted', N'Request Accepted', 1)");
            migrationBuilder.Sql("INSERT [Master].[AccountStatus] ([AccountStatusID], [AccountStatusName], [Description], IsActive) VALUES (5, N'Activated', N'Activated', 1)");
            migrationBuilder.Sql("INSERT [Master].[AccountStatus] ([AccountStatusID], [AccountStatusName], [Description], IsActive) VALUES (6, N'Deactivated', N'Deactivated', 1)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[AccountStatus] OFF");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Country] ON ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (1,  1, N'Afghanistan', 93, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (2,  1, N'Albania', 355, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (3,  1, N'Algeria', 213, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (4,  1, N'Andorra', 376, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (5,  1, N'Angola', 244, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (6,  1, N'Antigua and Barbuda', 1268, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (7,  1, N'Argentina', 54, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (8,  1, N'Armenia', 374, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (9,  1, N'Aruba', 297, 2)	 ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (10,  1, N'Australia', 61, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (11,  1, N'Austria', 43, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (12,  1, N'Azerbaijan', 994, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (13,  1, N'Bahamas', 1242, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (14,  1, N'Bahrain', 973, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (15,  1, N'Bangladesh', 880, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (16,  1, N'Barbados', 1246, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (17,  1, N'Belarus', 375, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (18,  1, N'Belgium', 32, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (19,  1, N'Belize', 501, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (20,  1, N'Benin', 229, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (21,  1, N'Bermuda', 1441, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (22,  1, N'Bhutan', 975, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (23,  1, N'Bolivia', 591, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (24,  1, N'Bosnia and Herzegovina', 387, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (25,  1, N'Botswana', 267, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (26,  1, N'Brazil', 55, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (27,  1, N'Brunei', 673, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (28,  1, N'Bulgaria', 359, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (29,  1, N'Burkina Faso', 226, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (30,  1, N'Burma', 95, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (31,  1, N'Burundi', 257, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (32,  1, N'Cambodia', 855, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (33,  1, N'Cameroon', 237, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (34,  1, N'Canada', 1, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (35,  1, N'Cabo Verde', 238, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (36,  1, N'Central African Republic', 236, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (37,  1, N'Chad', 235, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (38,  1, N'Chile', 56, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (39,  1, N'China', 86, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (40,  1, N'Colombia', 57, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (41,  1, N'Comoros', 269, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (42,  1, N'Congo, Kinshasa', 243, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (43,  1, N'Congo, Brazzaville', 242, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (44,  1, N'Costa Rica', 506, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (45,  1, N'Cote d''Ivoire', 225, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (46,  1, N'Croatia', 385, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (47,  1, N'Cuba', 53, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (48,  1, N'Curacao', 599, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (49,  1, N'Cyprus', 357, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (50,  1, N'Czechia', 420, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (51,  1, N'Denmark', 45, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (52,  1, N'Djibouti', 253, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (53,  1, N'Dominica', 1767, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (54,  1, N'Dominican Republic', 1809, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (55,  1, N'Ecuador', 593, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (56,  1, N'Egypt', 20, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (57,  1, N'El Salvador', 503, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (58,  1, N'Equatorial Guinea', 240, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (59,  1, N'Eritrea', 291, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (60,  1, N'Estonia', 372, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (61,  1, N'Ethiopia', 251, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (62,  1, N'Fiji', 679, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (63,  1, N'Finland', 358, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (64,  1, N'France', 33, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (65,  1, N'Gabon', 241, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (66,  1, N'Gambia, The', 220, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (67,  1, N'Georgia', 995, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (68,  1, N'Germany', 49, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (69,  1, N'Ghana', 233, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (70,  1, N'Greece', 30, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (71,  1, N'Grenada', 1473, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (72,  1, N'Guatemala', 502, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (73,  1, N'Guinea', 224, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (74,  1, N'Guinea-Bissau', 245, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (75,  1, N'Guyana', 592, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (76,  1, N'Haiti', 509, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (77,  1, N'Holy See', 379, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (78,  1, N'Honduras', 504, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (79,  1, N'Hong Kong', 852, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (80,  1, N'Hungary', 36, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (81,  1, N'Iceland', 354, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (82,  1, N'India', 91, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (83,  1, N'Indonesia', 62, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (84,  1, N'Iran', 98, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (85,  1, N'Iraq', 964, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (86,  1, N'Ireland', 353, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (87,  1, N'Israel', 972, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (88,  1, N'Italy', 39, 2)	 ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (89,  1, N'Jamaica', 1876, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (90,  1, N'Japan', 81, 2)	  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (91,  1, N'Jordan', 962, 2)  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (92,  1, N'Kazakhstan', 7, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (93,  1, N'Kenya', 254, 2)	  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (94,  1, N'Kiribati', 686, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (95,  1, N'Kosovo', 383, 2)  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (96,  1, N'Kuwait', 965, 2)  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (97,  1, N'Kyrgyzstan', 996, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (98,  1, N'Laos', 856, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (99,  1, N'Latvia', 371, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (100,  1, N'Lebanon', 961, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (101,  1, N'Lesotho', 266, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (102,  1, N'Liberia', 231, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (103,  1, N'Libya', 218, 2)  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (104,  1, N'Liechtenstein', 423, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (105,  1, N'Lithuania', 370, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (106,  1, N'Luxembourg', 352, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (107,  1, N'Macau', 853, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (108,  1, N'Macedonia', 389, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (109,  1, N'Madagascar', 261, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (110,  1, N'Malawi', 265, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (111,  1, N'Malaysia', 60, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (112,  1, N'Maldives', 960, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (113,  1, N'Mali', 223, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (114,  1, N'Malta', 356, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (115,  1, N'Marshall Islands', 692, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (116,  1, N'Mauritania', 222, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (117,  1, N'Mauritius', 230, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (118,  1, N'Mexico', 52, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (119,  1, N'Micronesia', 691, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (120,  1, N'Moldova', 373, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (121,  1, N'Monaco', 377, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (122,  1, N'Mongolia', 976, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (123,  1, N'Montenegro', 382, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (124,  1, N'Morocco', 212, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (125,  1, N'Mozambique', 258, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (126,  1, N'Namibia', 264, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (127,  1, N'Nauru', 674, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (128,  1, N'Nepal', 977, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (129,  1, N'Netherlands', 31, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (130,  1, N'New Zealand', 64, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (131,  1, N'Nicaragua', 505, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (132,  1, N'Niger', 227, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (133,  1, N'Nigeria', 234, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (134,  1, N'North Korea', 850, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (135,  1, N'Norway', 47, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (136,  1, N'Oman', 968, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (137,  1, N'Pakistan', 92, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (138,  1, N'Palau', 680, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (139,  1, N'Palestinian Territories', 970, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (140,  1, N'Panama', 507, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (141,  1, N'Papua New Guinea', 675, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (142,  1, N'Paraguay', 595, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (143,  1, N'Peru', 51, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (144,  1, N'Philippines', 63, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (145,  1, N'Poland', 48, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (146,  1, N'Portugal', 351, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (147,  1, N'Qatar', 974, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (148,  1, N'Romania', 40, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (149,  1, N'Rwanda', 250, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (150,  1, N'Saint Kitts and Nevis', 1869, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (151,  1, N'Saint Lucia', 1758, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (152,  1, N'Saint Vincent Grenadines', 1784, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (153,  1, N'Samoa', 685, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (154,  1, N'San Marino', 378, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (155,  1, N'Sao Tome and Principe', 239, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (156,  1, N'Saudi Arabia', 966, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (157,  1, N'Senegal', 221, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (158,  1, N'Serbia', 381, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (159,  1, N'Seychelles', 248, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (160,  1, N'Sierra Leone', 232, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (161,  1, N'Singapore', 65, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (162,  1, N'Sint Maarten', 1721, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (163,  1, N'Slovakia', 421, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (164,  1, N'Slovenia', 386, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (165,  1, N'Solomon Islands', 677, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (166,  1, N'Somalia', 252, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (167,  1, N'South Africa', 27, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (168,  1, N'South Korea', 82, 2)  ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (169,  1, N'South Sudan', 211, 2) ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (170,  1, N'Spain', 34, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (171,  1, N'Sri Lanka', 94, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (172,  1, N'Sudan', 249, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (173,  1, N'Suriname', 597, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (174,  1, N'Swaziland', 268, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (175,  1, N'Sweden', 46, 2)	");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (176,  1, N'Switzerland', 41, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (177,  1, N'Syria', 963, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (178,  1, N'Taiwan', 886, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (179,  1, N'Tajikistan', 992, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (180,  1, N'Tanzania', 255, 2)	 ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (181,  1, N'Thailand', 66, 2)	 ");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (182,  1, N'Timor-Leste', 670, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (183,  1, N'Togo', 228, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (184,  1, N'Tonga', 676, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (185,  1, N'Trinidad and Tobago', 1868, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (186,  1, N'Tunisia', 216, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (187,  1, N'Turkey', 90, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (188,  1, N'Turkmenistan', 993, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (189,  1, N'Tuvalu', 688, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (190,  1, N'Uganda', 256, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (191,  1, N'Ukraine', 380, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (192,  1, N'United Arab Emirates', 971, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (193,  1, N'United Kingdom', 44, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (194,  1, N'Uruguay', 598, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (195,  1, N'Uzbekistan', 998, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (196,  1, N'Vanuatu', 678, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (197,  1, N'Venezuela', 58, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (198,  1, N'Vietnam', 84, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (199,  1, N'Yemen', 967, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (200,  1, N'Zambia', 260, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (201,  1, N'Zimbabwe', 263, 2)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (202,  1, N'United States', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[Country] ([CountryID], [IsActive], [CountryName], [CountryCallingCode], [DisplayOrder]) VALUES (203,  1, N'Zimbabwe', 263, 2)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Country] OFF");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Salutation]  ON ");
            migrationBuilder.Sql("INSERT [Master].[Salutation] ([SalutationID],  [IsActive], [SalutationName], [DisplayOrder]) VALUES (1,  1, N'Dr.', NULL)");
            migrationBuilder.Sql("INSERT [Master].[Salutation] ([SalutationID],  [IsActive], [SalutationName], [DisplayOrder]) VALUES (2,  1, N'Mr.', NULL)");
            migrationBuilder.Sql("INSERT [Master].[Salutation] ([SalutationID],  [IsActive], [SalutationName], [DisplayOrder]) VALUES (3,  1, N'Mrs.', NULL)");
            migrationBuilder.Sql("INSERT [Master].[Salutation] ([SalutationID],  [IsActive], [SalutationName], [DisplayOrder]) VALUES (4,  1, N'Ms.', NULL)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Salutation] OFF");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[State] ON ");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (1,  1, N'Alabama', NULL, N'AL')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (2,  1, N'Alaska', NULL, N'AK') ");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (3,  1, N'Arizona', NULL, N'AZ')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (4,  1, N'Arkansas', NULL, N'AR')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (5,  1, N'California', NULL, N'CA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (6,  1, N'Colorado', NULL, N'CO')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (7,  1, N'Connecticut', NULL, N'CT')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (8,  1, N'Delaware', NULL, N'DE')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (9,  1, N'Dist. of Columbia', NULL, N'DC')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (10,  1, N'Florida', NULL, N'FL')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (11,  1, N'Georgia', NULL, N'GA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (12,  1, N'Hawaii', NULL, N'HI') ");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (13,  1, N'Idaho', NULL, N'ID')  ");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (14,  1, N'Illinois', NULL, N'IL')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (15,  1, N'Indiana', NULL, N'IN')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (16,  1, N'Iowa', NULL, N'IA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (17,  1, N'Kansas', NULL, N'KS')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (18,  1, N'Kentucky', NULL, N'KY')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (19,  1, N'Louisiana', NULL, N'LA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (20,  1, N'Maine', NULL, N'ME')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (21,  1, N'Maryland', NULL, N'MD')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (22,  1, N'Massachusetts', NULL, N'MA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (23,  1, N'Michigan', NULL, N'MI')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (24,  1, N'Minnesota', NULL, N'MN')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (25,  1, N'Mississippi', NULL, N'MS')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (26,  1, N'Missouri', NULL, N'MO')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (27,  1, N'Montana', NULL, N'MT')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (28,  1, N'Nebraska', NULL, N'NE')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (29,  1, N'Nevada', NULL, N'NV')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (30,  1, N'New Hampshire', NULL, N'NH')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (31,  1, N'New Jersey', NULL, N'NJ')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (32,  1, N'New Mexico', NULL, N'NM')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (33,  1, N'New York', NULL, N'NY')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (34,  1, N'North Carolina', NULL, N'NC')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (35,  1, N'North Dakota', NULL, N'ND')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (36,  1, N'Ohio', NULL, N'OH')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (37,  1, N'Oklahoma', NULL, N'OK')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (38,  1, N'Oregon', NULL, N'OR')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (39,  1, N'Pennsylvania', NULL, N'PA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (40,  1, N'Puerto Rico', NULL, N'PR')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (41,  1, N'Rhode Island', NULL, N'RI')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (42,  1, N'South Carolina', NULL, N'SC')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (43,  1, N'South Dakota', NULL, N'SD')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (44,  1, N'Tennessee', NULL, N'TN')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (45,  1, N'Texas', NULL, N'TX')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (46,  1, N'Utah', NULL, N'UT')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (47,  1, N'Vermont', NULL, N'VT')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (48,  1, N'Virginia', NULL, N'VA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (49,  1, N'Washington', NULL, N'WA')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (50,  1, N'West Virginia', NULL, N'WV')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (51,  1, N'Wisconsin', NULL, N'WI')");
            migrationBuilder.Sql("INSERT [Master].[State] ([StateID],  [IsActive], [StateName], [DisplayOrder], [StateCode]) VALUES (52,  1, N'Wyoming', NULL, N'WY')");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[State] OFF");


            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Role] ON ");

            migrationBuilder.Sql("INSERT [Master].[Role] ([RoleID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [RoleName], [RoleDescription], [DisplayOrder], [IsLoginRole]) VALUES (1, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, 1, N'Administrator', N'NUL Administrator', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[Role] ([RoleID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [RoleName], [RoleDescription], [DisplayOrder], [IsLoginRole]) VALUES (2, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, 1, N'Borrower', N'Borrower', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[Role] ([RoleID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [RoleName], [RoleDescription], [DisplayOrder], [IsLoginRole]) VALUES (3, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, 1, N'UnderWriter', N'NUL UnderWriter', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[Role] ([RoleID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [RoleName], [RoleDescription], [DisplayOrder], [IsLoginRole]) VALUES (4, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, 1, N'NULTreasury', N'NUL CFO/Treasury', 1, 0)");
            migrationBuilder.Sql("INSERT [Master].[Role] ([RoleID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [RoleName], [RoleDescription], [DisplayOrder], [IsLoginRole]) VALUES (5, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-27 00:00:00.000' AS DateTime), 7, 1, N'Loan Processor', N'Loan Processor', 1, 0)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Role] OFF ");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Ethnicity] ON ");

            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (1, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'American Indian or Alaska Native', 1, 4)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (2, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Asian', 1, 5)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (3, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Black or African American', 1, 6)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (4, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Race and Ethnicity Unknown', 0, 2)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (5, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Hispanics of any race', 1, 3)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (6, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Native Hawaiian or Other Pacific Islander', 1, 7)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Non Resident Alien', 0, 1)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (8, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Two or more races', 1, 9)");
            migrationBuilder.Sql("INSERT [Master].[Ethnicity] ([EthnicityID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [EthnicityName], [IsMinority], [DisplayOrder]) VALUES (9, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'White', 0, 8)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Ethnicity] OFF");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Gender] ON ");

            migrationBuilder.Sql("INSERT [Master].[Gender] ([GenderID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [GenderName], [DisplayOrder]) VALUES (1, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Male', 1)");
            migrationBuilder.Sql("INSERT [Master].[Gender] ([GenderID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [GenderName], [DisplayOrder]) VALUES (2, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Female', 2)");
            migrationBuilder.Sql("INSERT [Master].[Gender] ([GenderID], [CreatedDateTime], [CreatedByUserID], [LastModifiedDateTime], [LastModifiedByUserID], [IsActive], [GenderName], [DisplayOrder]) VALUES (3, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, CAST(N'2017-10-10 00:00:00.000' AS DateTime), 7, 1, N'Other/Not Reported', 3)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[Gender] OFF");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[BusinessRole] ON ");
            migrationBuilder.Sql("INSERT [Master].[BusinessRole] ([BusinessRoleID], [BusinessRoleName], [Description], [IsActive], [DisplayOrder]) VALUES (1, N'Owner', N'BusinessOwner', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[BusinessRole] ([BusinessRoleID], [BusinessRoleName], [Description], [IsActive], [DisplayOrder]) VALUES (2, N'Co-Owner', N'Business Co-Owner', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[BusinessRole] ([BusinessRoleID], [BusinessRoleName], [Description], [IsActive], [DisplayOrder]) VALUES (3, N'CFO', N'Business CFO', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[BusinessRole] ([BusinessRoleID], [BusinessRoleName], [Description], [IsActive], [DisplayOrder]) VALUES (4, N'Staff Member', N'Business Staff Member', 1, 1)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[BusinessRole] OFF ");

            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[UrbanLeagueAffiliate] ON ");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (1, N'Urban League of Greater Atlanta', N'Urban League of Greater Atlanta', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (2, N'Greater Baltimore Urban League', N'Greater Baltimore Urban League ', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (3, N'Chicago Urban League', N'Chicago Urban League', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (4, N'Urban League of Greater Southwestern Ohio', N'Urban League of Greater Southwestern Ohio', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (5, N'Urban League of Greater Cleveland ', N'Urban League of Greater Cleveland ', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (6, N'Houston Area Urban League', N'Houston Area Urban League', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (7, N'Jacksonville Urban League', N'Jacksonville Urban League', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (8, N'Greater Washington Urban League', N'Greater Washington Urban League', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (9, N'Urban League of Philadelphia', N'Urban League of Philadelphia', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (10, N'Los Angeles Urban League', N'Los Angeles Urban League', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (11, N'Urban League of Louisiana', N'Urban League of Louisiana', 1, 1)");
            migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (12, N'Las Vegas - Clark County Urban League', N'Las Vegas - Clark County Urban League', 1, 1)");
           // migrationBuilder.Sql("INSERT [Master].[UrbanLeagueAffiliate] ([AffiliateID], [AffiliateName], [Description], [IsActive], [DisplayOrder]) VALUES (13, N'Greater Cincinnati Urban League', N'Greater Cincinnati Urban League', 1, 1)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [Master].[UrbanLeagueAffiliate] OFF ");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("delete from [Master].[AccountStatus] where AccountStatusID between 1 and 6");
            migrationBuilder.Sql("delete from [Master].[Country] where CountryID between 1 and 203");
            migrationBuilder.Sql("delete from [Master].[Salutation] where SalutationID between 1 and 4"); ;
            migrationBuilder.Sql("delete from [Master].[State] where StateID between 1 and 52");
            migrationBuilder.Sql("delete from [Master].[Role] where RoleID between 1 and 5");
            migrationBuilder.Sql("delete from [Master].[Ethnicity] where EthnicityID between 1 and 9");
            migrationBuilder.Sql("delete from [Master].[Gender] where GenderID between 1 and 3");
            migrationBuilder.Sql("delete from [Master].[BusinessRole] where BusinessRoleID between 1 and 4");
            migrationBuilder.Sql("delete from [Master].[UrbanLeagueAffiliate] where AffiliateID between 1 and 12");
        }
    }
}
