using Microsoft.EntityFrameworkCore.Migrations;

namespace ThoughtFocus.DataAccess.Migrations
{
    public partial class DML_ProgramInvitation_Notification : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
             migrationBuilder.Sql("UPDATE [Master].[Notification] SET [Body] =  N'<table width=''100%'' border=''0'' cellspacing=''10'' cellpadding=''0''> <tr> <td class=''bodycopy''> Welcome to the BuildBackBlack platform.  <br /><br /> </td> </tr> <tr> <td class=''bodycopy''> You are receiving this email because National Urban League has created an account in your name. Please click on ''Activate Account'' to activate the account. You will be directed to a page where you will be asked to set your password to gain access to the platform.<br /><br /> </td> </tr> <tr> <td style=''padding: 20px 0 20px 180px;''> <table class=''buttonwrapper'' border=''0'' cellspacing=''0'' cellpadding=''0''> <tr> <td style=''font-family: sans-serif; font-size: 14px; vertical-align: top; background-color: #277812; border-radius: 5px; text-align: center;'' class=''btn-primary''> <a href= @CallBackURL target=''_blank'' style=''display: inline-block; color: #ffffff; background-color: #C11439; border: solid 1px #277812; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-transform: capitalize; border-color: #C11439;''>Activate Account</a> </td> </tr> </table> </td> </tr> <tr> <td class=''bodycopy''><br /> @AdditionalMessage </td> </tr> <tr> <td class=''bodycopy''><br /> Please direct any questions or problems regarding this email to contactus@buildbackblack.org for assistance. <br /> </td> </tr> <tr> <td><br /> </td> </tr> <tr> <td class=''bodycopy''> Sincerely,<br /> National Urban League </td> </tr> </table> </td> </tr> <tr>' WHERE [NotificationID] = 1 ");

            migrationBuilder.Sql("UPDATE [Master].[Notification] SET [Body] =  N'<table width=''100%'' border=''0'' cellspacing=''10'' cellpadding=''0''> <tr> <td class=''bodycopy''> The National Urban League invites @BusinessName to submit a grant application for consideration. This request is confidential and is prepared for the sole use of your business and should not be distributed to other businesses. Several items will need to be attached during the application submission process. Required attachments will include an electronic or scanned copy of your: <br /> </td> </tr> <tr> <td class=''bodycopy''> <ul> <li> Form W-9 - Request for Taxpayer Identification Number and Certification </li> <li> Certificate of Good Standing (*not required for sole proprietorships) </li> <li> Proof of Ownership </li> <li> ACH Vendor Form </li> <li> If this is for loans and grants, there will likely be other documents required such as financial statements </li> </ul> </td> </tr> <tr> <td class=''bodycopy''> <br /> @CallBackURL </td> </tr> <tr> <td class=''bodycopy''> <br /> Your request will be reviewed promptly, and you can expect a formal response to your application within @TimeFrame. If you need additional information or have any questions, please contact Stephanie DeVane via email @EmailAddress. We look forward to receiving your application. <br /> </td> </tr> <tr> <td><br /> </td> </tr>' WHERE [NotificationID] = 2 ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
             migrationBuilder.Sql("UPDATE [Master].[Notification] SET [Body] =  N'<table width=''100%'' border=''0'' cellspacing=''10'' cellpadding=''0''> <tr> <td class=''bodycopy''> Welcome to the BuildBackBlack platform.  <br /><br /> </td> </tr> <tr> <td class=''bodycopy''> You are receiving this email because NUL has created an account in your name. Please click on ''Activate Account'' to activate the account. You will be directed to a page where you will be asked to set your password to gain access to the platform. <br /><br /> </td> </tr> <tr> <td style=''padding: 20px 0 20px 180px;''> <table class=''buttonwrapper'' border=''0'' cellspacing=''0'' cellpadding=''0''> <tr> <td style=''font-family: sans-serif; font-size: 14px; vertical-align: top; background-color: #277812; border-radius: 5px; text-align: center;'' class=''btn-primary''> <a href= @CallBackURL target=''_blank'' style=''display: inline-block; color: #ffffff; background-color: #C11439; border: solid 1px #277812; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-transform: capitalize; border-color: #C11439;''>Activate Account</a> </td> </tr> </table> </td> </tr> <tr> <td class=''bodycopy''><br /> @AdditionalMessage </td> </tr> <tr> <td class=''bodycopy''><br /> Please direct any questions or problems regarding this email to contactus@buildbackblack.org for assistance. <br /> </td> </tr> <tr> <td><br /> </td> </tr> <tr> <td class=''bodycopy''> Sincerely,<br /> . NUL </td> </tr> </table> </td> </tr> <tr>' WHERE [NotificationID] = 1 ");

             migrationBuilder.Sql("UPDATE [Master].[Notification] SET [Body] =  N'<table width=''100%'' border=''0'' cellspacing=''10'' cellpadding=''0''> <tr> <td class=''bodycopy''> The National Urban League invites @BusinessName to submit a [grant/loan] application for consideration. This request is confidential and is prepared for the sole use of your business and should not be distributed to other businesses. Several items will need to be attached during the application submission process. Required attachments will include an electronic or scanned copy of your: <br /> </td> </tr> <tr> <td class=''bodycopy''> <ul> <li> Form W-9 - Request for Taxpayer Identification Number and Certification </li> <li> Certificate of Good Standing (*not required for sole proprietorships) </li> <li> Proof of Ownership </li> <li> ACH Vendor Form </li> <li> If this is for loans and grants, there will likely be other documents required such as financial statements </li> </ul> </td> </tr> <tr> <td class=''bodycopy''> <br /> You may begin a NEW application at the following link: @CallBackURL </td> </tr> <tr> <td class=''bodycopy''> <br /> Your request will be reviewed promptly, and you can expect a formal response to your application within @TimeFrame. If you need additional information or have any questions, please contact Stephanie DeVane via email @EmailAddress. We look forward to receiving your application. <br /> </td> </tr> <tr> <td><br /> </td> </tr>' WHERE [NotificationID] = 2 ");
        }
    }
}
