// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThoughtFocus.DataAccess;

namespace ThoughtFocus.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210416121513_FundingSourceTableNamesModified")]
    partial class FundingSourceTableNamesModified
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.BusinessOwner", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Demographic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EthnicityID")
                        .HasColumnType("bigint");

                    b.Property<long>("GenderID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LoanApplicationID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OwnedPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RaceID")
                        .HasColumnType("bigint");

                    b.Property<long>("VeteranID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("EthnicityID");

                    b.HasIndex("GenderID");

                    b.HasIndex("LoanApplicationID");

                    b.HasIndex("RaceID");

                    b.HasIndex("VeteranID");

                    b.ToTable("BusinessOwner", "Application");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanApplicantDetails", b =>
                {
                    b.Property<long>("LoanApplicantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BusinessRoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LoanApplicationID")
                        .HasColumnType("bigint");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SalutationID")
                        .HasColumnType("bigint");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanApplicantID");

                    b.HasIndex("BusinessRoleID");

                    b.HasIndex("ContactID");

                    b.HasIndex("LoanApplicationID");

                    b.HasIndex("SalutationID");

                    b.HasIndex("StateID");

                    b.ToTable("LoanApplicantDetails", "Application");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanApplication", b =>
                {
                    b.Property<long>("LoanApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConcentAcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConcentAccepted")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoanNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanApplicationID");

                    b.HasIndex("ApplicationStatusID");

                    b.HasIndex("ApplicationTypeID");

                    b.ToTable("LoanApplication", "Application");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanBusinessDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AffiliateID")
                        .HasColumnType("bigint");

                    b.Property<long>("AverageMonthlyPayroll")
                        .HasColumnType("bigint");

                    b.Property<long>("BankAccountNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("BankRoutingNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BusinessTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DBA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DUNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeStrength")
                        .HasColumnType("bigint");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IndustryTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("LoanApplicationID")
                        .HasColumnType("bigint");

                    b.Property<string>("NAICS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumberOfYearsInBusiness")
                        .HasColumnType("bigint");

                    b.Property<string>("SIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AffiliateID");

                    b.HasIndex("BusinessTypeID");

                    b.HasIndex("IndustryTypeID");

                    b.HasIndex("LoanApplicationID")
                        .IsUnique();

                    b.HasIndex("StateID");

                    b.ToTable("LoanBusinessDetail", "Application");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.ApplicationDocument", b =>
                {
                    b.Property<long>("ApplicationDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DocumentID")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("LoanApplicationID")
                        .HasColumnType("bigint");

                    b.HasKey("ApplicationDocumentID");

                    b.HasIndex("DocumentTypeID");

                    b.HasIndex("LoanApplicationID");

                    b.ToTable("ApplicationDocuments", "Application");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.ApplicationDocumentRequestLog", b =>
                {
                    b.Property<long>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<long>("LoanApplicationID")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.HasKey("RequestID");

                    b.ToTable("ApplicationDocumentRequestLog", "Application");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Audit.AuditSessionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrowserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrowserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrowserVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditSessionDetails", "Audit");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Audit.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditTrail", "Audit");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.Contact", b =>
                {
                    b.Property<long>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccountStatusID")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SalutationID")
                        .HasColumnType("bigint");

                    b.HasKey("ContactID");

                    b.HasIndex("AccountStatusID");

                    b.HasIndex("SalutationID");

                    b.ToTable("Contacts", "Contact");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Contact");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.DocumentCategory", b =>
                {
                    b.Property<int>("DocumentCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentCategoryID");

                    b.ToTable("DocumentCategorys", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<int?>("DocumentCategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentTypeID");

                    b.HasIndex("DocumentCategoryID");

                    b.ToTable("DocumentTypes", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FundingSourceID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginatingBankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FundingSourceID");

                    b.HasIndex("TransactionTypeID");

                    b.ToTable("FundTransactions", "FundingSource");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FundTransaction");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundTransactionDocument", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<long>("FundTransactionID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DocumentTypeID");

                    b.HasIndex("FundTransactionID");

                    b.ToTable("FundTransactionDocuments", "FundingSource");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingEntity", b =>
                {
                    b.Property<long>("FundingEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundingEntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TIN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundingEntityID");

                    b.ToTable("FundingEntities", "FundingSource");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSource", b =>
                {
                    b.Property<long>("FundingSourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FundingEntityID")
                        .HasColumnType("bigint");

                    b.Property<int>("FundingTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialFundedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundingSourceID");

                    b.HasIndex("FundingEntityID");

                    b.HasIndex("FundingTypeID");

                    b.ToTable("FundingSources", "FundingSource");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSourceBusinessTypes", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BusinessTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FundingSourceID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BusinessTypeID");

                    b.HasIndex("FundingSourceID");

                    b.ToTable("FundingSourceBusinessTypes", "FundingSource");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSourceStates", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FundingSourceID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("FundingSourceID");

                    b.HasIndex("StateID");

                    b.ToTable("FundingSourceStates", "FundingSource");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.AccountStatus", b =>
                {
                    b.Property<long>("AccountStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AccountStatusID");

                    b.ToTable("AccountStatus", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Action", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionID");

                    b.ToTable("Action", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Affiliate", b =>
                {
                    b.Property<long>("AffiliateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AffiliateID");

                    b.ToTable("Affiliate", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.ApplicationStatus", b =>
                {
                    b.Property<int>("ApplicationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationStatusID");

                    b.ToTable("ApplicationStatus", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.ApplicationType", b =>
                {
                    b.Property<int>("ApplicationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationTypeID");

                    b.ToTable("ApplicationType", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.BusinessRole", b =>
                {
                    b.Property<long>("BusinessRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BusinessRoleID");

                    b.ToTable("BusinessRole", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.BusinessType", b =>
                {
                    b.Property<long>("BusinessTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessTypeID");

                    b.ToTable("BusinessType", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Country", b =>
                {
                    b.Property<long>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CountryCallingCode")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryID");

                    b.ToTable("Country", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Ethnicity", b =>
                {
                    b.Property<long>("EthnicityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("EthnicityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMinority")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EthnicityID");

                    b.ToTable("Ethnicity", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.FundingType", b =>
                {
                    b.Property<int>("FundingTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundingTypeID");

                    b.ToTable("FundingTypes", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Gender", b =>
                {
                    b.Property<long>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("GenderID");

                    b.ToTable("Gender", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.IndustryType", b =>
                {
                    b.Property<long>("IndustryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndustryTypeID");

                    b.ToTable("IndustryType", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Menu", b =>
                {
                    b.Property<long>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuID");

                    b.ToTable("Menu", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RMRoleMenuSubMenu", b =>
                {
                    b.Property<long>("RoleMenuSubMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubMenuID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleMenuSubMenuID");

                    b.HasIndex("MenuID");

                    b.HasIndex("RoleID");

                    b.HasIndex("SubMenuID");

                    b.ToTable("RMRoleMenuSubMenu", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Race", b =>
                {
                    b.Property<long>("RaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RaceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaceID");

                    b.ToTable("Race", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoginRole")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Role", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RolePermission", b =>
                {
                    b.Property<long>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActionID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("ActionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermission", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Salutation", b =>
                {
                    b.Property<long>("SalutationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SalutationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalutationID");

                    b.ToTable("Salutation", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SecurityQuestion", b =>
                {
                    b.Property<long>("SecurityQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityQuestionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecurityQuestionID");

                    b.ToTable("SecurityQuestion", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.State", b =>
                {
                    b.Property<long>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.ToTable("State", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SubMenu", b =>
                {
                    b.Property<long>("SubMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<string>("SubMenuDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubMenuID");

                    b.HasIndex("MenuID");

                    b.ToTable("SubMenu", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionTypeID");

                    b.ToTable("TransactionTypes", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.UrbanLeagueAffiliate", b =>
                {
                    b.Property<long>("AffiliateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AffiliateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AffiliateID");

                    b.ToTable("UrbanLeagueAffiliate", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Veteran", b =>
                {
                    b.Property<long>("VeteranID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("VeteranType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VeteranID");

                    b.ToTable("Veteran", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AccountActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedLoginAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedLoginAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedPasswordAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedPasswordAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdentityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAccountActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLockoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPasswordChangedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("ContactID")
                        .IsUnique();

                    b.ToTable("Users", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserPasswordResetInfo", b =>
                {
                    b.Property<long>("UserPasswordResetInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsAdminOrSelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpiry")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordResetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserPasswordResetInfoID");

                    b.ToTable("UserPasswordResetInfo", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserProfileLoginInfo", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AccountActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedLoginAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedLoginAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedPasswordAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedPasswordAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccountActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLockoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPasswordChangedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("UserProfileLoginInfo", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserRole", b =>
                {
                    b.Property<long>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.BusinessContact", b =>
                {
                    b.HasBaseType("ThoughtFocus.DataAccess.Models.Contact.Contact");

                    b.Property<long>("AffiliateID")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessID")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessRoleID")
                        .HasColumnType("bigint");

                    b.HasIndex("AffiliateID");

                    b.HasIndex("BusinessRoleID");

                    b.ToTable("Contacts", "Contact");

                    b.HasDiscriminator().HasValue("BusinessContact");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundUtilization", b =>
                {
                    b.HasBaseType("ThoughtFocus.DataAccess.Models.FundingSource.FundTransaction");

                    b.Property<long>("ApplicationID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateofDisbursement")
                        .HasColumnType("datetime2");

                    b.HasIndex("ApplicationID");

                    b.ToTable("FundTransactions", "FundingSource");

                    b.HasDiscriminator().HasValue("FundUtilization");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.BusinessOwner", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Ethnicity", "Ethnicity")
                        .WithMany()
                        .HasForeignKey("EthnicityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Application.LoanApplication", "LoanApplication")
                        .WithMany("BusinessOwners")
                        .HasForeignKey("LoanApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Veteran", "Veteran")
                        .WithMany()
                        .HasForeignKey("VeteranID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ethnicity");

                    b.Navigation("Gender");

                    b.Navigation("LoanApplication");

                    b.Navigation("Race");

                    b.Navigation("Veteran");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanApplicantDetails", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.BusinessRole", "BusinessRole")
                        .WithMany()
                        .HasForeignKey("BusinessRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Contact.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Application.LoanApplication", "LoanApplication")
                        .WithMany("LoanApplicantDetails")
                        .HasForeignKey("LoanApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.State", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessRole");

                    b.Navigation("Contact");

                    b.Navigation("LoanApplication");

                    b.Navigation("Salutation");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanApplication", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.ApplicationStatus", "ApplicationStatus")
                        .WithMany()
                        .HasForeignKey("ApplicationStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.ApplicationType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("ApplicationType");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanBusinessDetail", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Affiliate", "Affiliate")
                        .WithMany()
                        .HasForeignKey("AffiliateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.BusinessType", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.IndustryType", "IndustryType")
                        .WithMany()
                        .HasForeignKey("IndustryTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Application.LoanApplication", "LoanApplication")
                        .WithOne("LoanBusinessDetail")
                        .HasForeignKey("ThoughtFocus.DataAccess.Models.Application.LoanBusinessDetail", "LoanApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.State", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affiliate");

                    b.Navigation("BusinessType");

                    b.Navigation("IndustryType");

                    b.Navigation("LoanApplication");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.ApplicationDocument", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.DocumentType", "DocumentType")
                        .WithMany("ApplicationDocuments")
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Application.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.Contact", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.AccountStatus", "AccountStatus")
                        .WithMany()
                        .HasForeignKey("AccountStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatus");

                    b.Navigation("Salutation");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.DocumentType", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.DocumentCategory", "DocumentCategory")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("DocumentCategoryID");

                    b.Navigation("DocumentCategory");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundTransaction", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.FundingSource.FundingSource", "FundingSource")
                        .WithMany("FundTransactions")
                        .HasForeignKey("FundingSourceID");

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundingSource");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundTransactionDocument", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.FundingSource.FundTransaction", "FundTransaction")
                        .WithMany("FundTransactionDocuments")
                        .HasForeignKey("FundTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("FundTransaction");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSource", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.FundingSource.FundingEntity", "FundingEntity")
                        .WithMany()
                        .HasForeignKey("FundingEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.FundingType", "FundingType")
                        .WithMany()
                        .HasForeignKey("FundingTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundingEntity");

                    b.Navigation("FundingType");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSourceBusinessTypes", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.BusinessType", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.FundingSource.FundingSource", "FundingSource")
                        .WithMany("FundingSourceBusinessTypes")
                        .HasForeignKey("FundingSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");

                    b.Navigation("FundingSource");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSourceStates", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.FundingSource.FundingSource", "FundingSource")
                        .WithMany("FundingSourceStates")
                        .HasForeignKey("FundingSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.State", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundingSource");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RMRoleMenuSubMenu", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Menu", "Menu")
                        .WithMany("RMRoleMenuSubMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Role", "Role")
                        .WithMany("RMRoleMenuSubMenus")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.SubMenu", "SubMenu")
                        .WithMany("RMRoleMenuSubMenus")
                        .HasForeignKey("SubMenuID");

                    b.Navigation("Menu");

                    b.Navigation("Role");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RolePermission", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionID");

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SubMenu", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Menu", "Menu")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.User", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Contact.Contact", "Contact")
                        .WithOne("Users")
                        .HasForeignKey("ThoughtFocus.DataAccess.Models.User.User", "ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserRole", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Role", "Role")
                        .WithMany("RUserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.User.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.BusinessContact", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.UrbanLeagueAffiliate", "UrbanLeagueAffiliate")
                        .WithMany()
                        .HasForeignKey("AffiliateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.BusinessRole", "BusinessRole")
                        .WithMany()
                        .HasForeignKey("BusinessRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessRole");

                    b.Navigation("UrbanLeagueAffiliate");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundUtilization", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Application.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Application.LoanApplication", b =>
                {
                    b.Navigation("BusinessOwners");

                    b.Navigation("LoanApplicantDetails");

                    b.Navigation("LoanBusinessDetail");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.Contact", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.DocumentCategory", b =>
                {
                    b.Navigation("DocumentTypes");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.DocumentType", b =>
                {
                    b.Navigation("ApplicationDocuments");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundTransaction", b =>
                {
                    b.Navigation("FundTransactionDocuments");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.FundingSource.FundingSource", b =>
                {
                    b.Navigation("FundingSourceBusinessTypes");

                    b.Navigation("FundingSourceStates");

                    b.Navigation("FundTransactions");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Menu", b =>
                {
                    b.Navigation("RMRoleMenuSubMenus");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Role", b =>
                {
                    b.Navigation("RMRoleMenuSubMenus");

                    b.Navigation("RolePermissions");

                    b.Navigation("RUserRoles");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SubMenu", b =>
                {
                    b.Navigation("RMRoleMenuSubMenus");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
