// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThoughtFocus.DataAccess;

namespace ThoughtFocus.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210319103659_InitialdataSeedings")]
    partial class InitialdataSeedings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Audit.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AuditTrail", "Audit");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.Contact", b =>
                {
                    b.Property<long>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccountStatusID")
                        .HasColumnType("bigint");

                    b.Property<long>("AffiliateID")
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BusinessRoleID")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SalutationID")
                        .HasColumnType("bigint");

                    b.HasKey("ContactID");

                    b.HasIndex("AccountStatusID");

                    b.HasIndex("AffiliateID");

                    b.HasIndex("BusinessRoleID");

                    b.HasIndex("SalutationID");

                    b.ToTable("Contacts", "Contact");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.AccountStatus", b =>
                {
                    b.Property<long>("AccountStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AccountStatusID");

                    b.ToTable("AccountStatus", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Action", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionID");

                    b.ToTable("Action", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.BusinessRole", b =>
                {
                    b.Property<long>("BusinessRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BusinessRoleID");

                    b.ToTable("BusinessRole", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Country", b =>
                {
                    b.Property<long>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CountryCallingCode")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryID");

                    b.ToTable("Country", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Ethnicity", b =>
                {
                    b.Property<long>("EthnicityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("EthnicityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMinority")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EthnicityID");

                    b.ToTable("Ethnicity", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Gender", b =>
                {
                    b.Property<long>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("GenderID");

                    b.ToTable("Gender", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Menu", b =>
                {
                    b.Property<long>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuID");

                    b.ToTable("Menu", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RMRoleMenuSubMenu", b =>
                {
                    b.Property<long>("RoleMenuSubMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubMenuID")
                        .HasColumnType("bigint");

                    b.HasKey("RoleMenuSubMenuID");

                    b.HasIndex("MenuID");

                    b.HasIndex("RoleID");

                    b.HasIndex("SubMenuID");

                    b.ToTable("RMRoleMenuSubMenu", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoginRole")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Role", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RolePermission", b =>
                {
                    b.Property<long>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActionID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("ActionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermission", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Salutation", b =>
                {
                    b.Property<long>("SalutationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SalutationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalutationID");

                    b.ToTable("Salutation", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SecurityQuestion", b =>
                {
                    b.Property<long>("SecurityQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityQuestionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecurityQuestionID");

                    b.ToTable("SecurityQuestion", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.State", b =>
                {
                    b.Property<long>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.ToTable("State", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SubMenu", b =>
                {
                    b.Property<long>("SubMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<string>("SubMenuDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuIconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubMenuID");

                    b.HasIndex("MenuID");

                    b.ToTable("SubMenu", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.UrbanLeagueAffiliate", b =>
                {
                    b.Property<long>("AffiliateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AffiliateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AffiliateID");

                    b.ToTable("UrbanLeagueAffiliate", "Master");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AccountActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedLoginAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedLoginAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedPasswordAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedPasswordAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdentityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAccountActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLockoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPasswordChangedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("ContactID");

                    b.ToTable("Users", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserPasswordResetInfo", b =>
                {
                    b.Property<long>("UserPasswordResetInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsAdminOrSelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpiry")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordResetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserPasswordResetInfoID");

                    b.ToTable("UserPasswordResetInfo", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserProfileLoginInfo", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AccountActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedLoginAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedLoginAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FailedPasswordAttemptCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FailedPasswordAttemptDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccountActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLockoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPasswordChangedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("UserProfileLoginInfo", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserRole", b =>
                {
                    b.Property<long>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LastModifiedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole", "User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.Contact", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.AccountStatus", "AccountStatus")
                        .WithMany()
                        .HasForeignKey("AccountStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.UrbanLeagueAffiliate", "UrbanLeagueAffiliate")
                        .WithMany()
                        .HasForeignKey("AffiliateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.BusinessRole", "BusinessRole")
                        .WithMany()
                        .HasForeignKey("BusinessRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatus");

                    b.Navigation("BusinessRole");

                    b.Navigation("Salutation");

                    b.Navigation("UrbanLeagueAffiliate");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RMRoleMenuSubMenu", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Menu", "Menu")
                        .WithMany("RMRoleMenuSubMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Role", "Role")
                        .WithMany("RMRoleMenuSubMenus")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.SubMenu", "SubMenu")
                        .WithMany("RMRoleMenuSubMenus")
                        .HasForeignKey("SubMenuID");

                    b.Navigation("Menu");

                    b.Navigation("Role");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.RolePermission", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionID");

                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SubMenu", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Menu", "Menu")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.User", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Contact.Contact", "Contact")
                        .WithMany("Users")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.UserRole", b =>
                {
                    b.HasOne("ThoughtFocus.DataAccess.Models.Master.Role", "Role")
                        .WithMany("RUserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThoughtFocus.DataAccess.Models.User.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Contact.Contact", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Menu", b =>
                {
                    b.Navigation("RMRoleMenuSubMenus");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.Role", b =>
                {
                    b.Navigation("RMRoleMenuSubMenus");

                    b.Navigation("RolePermissions");

                    b.Navigation("RUserRoles");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.Master.SubMenu", b =>
                {
                    b.Navigation("RMRoleMenuSubMenus");
                });

            modelBuilder.Entity("ThoughtFocus.DataAccess.Models.User.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
