using Microsoft.EntityFrameworkCore.Migrations;

namespace ThoughtFocus.DataAccess.Migrations
{
    public partial class Add_SPA_WOrkFlow_tables4 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("SET IDENTITY_INSERT [WorkFlow].[RestrictionDefinition] ON");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (70, 1, 38, NULL, NULL, 9)    ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (71, 1, 42, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (72, 1, 43, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (73, 1, 44, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (74, 1, 45, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (75, 1, 46, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (76, 1, 47, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (77, 1, 48, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (78, 1, 49, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (79, 1, 50, NULL, NULL, 10)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (80, 1, 51, NULL, NULL, 11)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (81, 1, 52, NULL, NULL, 11)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (82, 1, 53, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (83, 1, 39, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (84, 1, 40, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (85, 1, 41, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (86, 1, 52, NULL, NULL, 13)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (87, 1, 42, NULL, NULL, 12)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (88, 1, 43, NULL, NULL, 12)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (89, 1, 45, NULL, NULL, 12)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (90, 1, 46, NULL, NULL, 12)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (91, 1, 42, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (92, 1, 43, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (93, 1, 45, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (94, 1, 46, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (95, 1, 50, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (96, 1, 38, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (97, 1, 39, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (98, 1, 40, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (99, 1, 41, NULL, NULL, 14)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (100, 1, 44, NULL, NULL, 14)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (101, 1, 49, NULL, NULL, 14)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (102, 1, 53, NULL, NULL, 14)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (103, 1, 54, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (104, 1, 54, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (105, 1, 55, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (106, 1, 55, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (107, 1, 56, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (108, 1, 56, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (109, 1, 55, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (110, 1, 57, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (111, 1, 58, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (112, 1, 59, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (113, 1, 60, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (114, 1, 61, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (115, 1, 61, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (116, 1, 62, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (117, 1, 62, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (118, 1, 63, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (119, 1, 64, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (120, 1, 64, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (121, 1, 65, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (122, 1, 66, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (123, 1, 67, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (124, 1, 68, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (125, 1, 69, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (126, 1, 63, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (127, 1, 63, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (128, 1, 70, NULL, NULL, 9)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (129, 1, 70, NULL, NULL, 14)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (130, 1, 71, NULL, NULL, 8)	  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (131, 1, 71, NULL, NULL, 10)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (132, 1, 71, NULL, NULL, 14)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (133, 1, 72, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (134, 1, 73, NULL, NULL, 11)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (135, 1, 73, NULL, NULL, 13)  ");
            migrationBuilder.Sql("INSERT [WorkFlow].[RestrictionDefinition] ([ID], [RestrictionType_Id], [Transition_ID], [ActorDefinitionExecuteRule_ID], [ActorDefinitionIsIdentity_ID], [ActorDefinitionIsInRole_ID]) VALUES (136, 1, 54, NULL, NULL, 10)  ");
            migrationBuilder.Sql("SET IDENTITY_INSERT [WorkFlow].[RestrictionDefinition] OFF");

            migrationBuilder.Sql("SET IDENTITY_INSERT [WorkFlow].[ParameterDefinition] ON ");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (21, N'System.Int64', 3, NULL, 2, N'ProcessId')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (22, N'System.String', 3, NULL, 2, N'PreviousState')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (23, N'System.String', 3, NULL, 2, N'CurrentState')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (24, N'System.String', 3, NULL, 2, N'PreviousStateForDirect')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (25, N'System.String', 3, NULL, 2, N'PreviousStateForReverse')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (26, N'System.String', 3, NULL, 2, N'PreviousActivity')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (27, N'System.String', 3, NULL, 2, N'CurrentActivity')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (28, N'System.String', 3, NULL, 2, N'PreviousActivityForDirect')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (29, N'System.String', 3, NULL, 2, N'PreviousActivityForReverse')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (30, N'System.String', 3, NULL, 2, N'CurrentCommand')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (31, N'System.String', 3, NULL, 2, N'ExecutedActivityState')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (32, N'System.Guid', 3, NULL, 2, N'IdentityId')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (33, N'System.Guid', 3, NULL, 2, N'ImpersonatedIdentityId')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (34, N'System.Guid', 3, NULL, 2, N'SchemeId')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (35, N'System.String', 3, NULL, 2, N'ProcessName')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (36, N'ThoughtFocus.Domain.User.UserSessionEntity,ThoughtFocus.Domain', 3, NULL, 2, N'UserSessionModel')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (37, N'System.String', 3, NULL, 2, N'Command')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (38, N'ThoughtFocus.Common.Workflow.Core.Model.ProcessInstance,ThoughtFocus.Common.Workflow.Core', 3, NULL, 2, N'ProcessInstance')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (39, N'ThoughtFocus.Domain.Params.FundUtilizationParam,ThoughtFocus.Domain', 3, NULL, 2, N'FundUtilization')");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinition] ([ID], [TypeAsString], [PurposeID], [SerializedDefaultValue], [WorkflowDefinitionID], [Name]) VALUES (40, N'System.String', 3, NULL, 2, N'Comment')");
            migrationBuilder.Sql("SET IDENTITY_INSERT [WorkFlow].[ParameterDefinition] OFF");

            migrationBuilder.Sql("SET IDENTITY_INSERT [WorkFlow].[ParameterDefinitionForAction] ON");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinitionForAction] ([ID], [IsInputParameter], [ParameterDefinitionID], [Order], [ActionDefinitionID]) VALUES (7, 1, 38, 1, 7)");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinitionForAction] ([ID], [IsInputParameter], [ParameterDefinitionID], [Order], [ActionDefinitionID]) VALUES (8, 1, 38, 1, 8)");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinitionForAction] ([ID], [IsInputParameter], [ParameterDefinitionID], [Order], [ActionDefinitionID]) VALUES (9, 1, 38, 1, 9)");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinitionForAction] ([ID], [IsInputParameter], [ParameterDefinitionID], [Order], [ActionDefinitionID]) VALUES (10, 1, 38, 1, 10)");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinitionForAction] ([ID], [IsInputParameter], [ParameterDefinitionID], [Order], [ActionDefinitionID]) VALUES (11, 1, 38, 1, 11)");
            migrationBuilder.Sql("INSERT [WorkFlow].[ParameterDefinitionForAction] ([ID], [IsInputParameter], [ParameterDefinitionID], [Order], [ActionDefinitionID]) VALUES (12, 1, 38, 1, 12)");
            migrationBuilder.Sql("SET IDENTITY_INSERT [WorkFlow].[ParameterDefinitionForAction] OFF");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
